name: CI # TODO

on:
  push:
    branches:
      - "${{ github.event.repository.default_branch }}"
      - "ci" # TODO: to remove
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - "${{ github.event.repository.default_branch }}"

env:
  IMAGE_NAME: "cdktf-bundle"
  IMAGE_PLATFORMS: "linux/amd64,linux/arm64"
  CDKTF_VERSION: "0.13.3"
  HADOLINT_VERSION: "v2.12.0"

jobs:

#  pre-commit:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-python@v4
#        with:
#          python-version: "3.11"
#      - uses: cloudposse/github-action-pre-commit@v3.0.0
#
#  static_analysis:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Dockerfile linting
#        # At the moment, the hadolint action is not usable as it does not display
#        # the errors in the logs in case of a failure.
#        # See: https://github.com/hadolint/hadolint-action/issues/60
#        # uses: hadolint/hadolint-action@v3.0.0
#        run: docker run --rm -i hadolint/hadolint:${HADOLINT_VERSION} < Dockerfile

  build_test_publish:
#    needs:
#      - pre-commit
#      - static_analysis
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language:
          - python
          - go
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
        with:
          platforms: ${{ env.IMAGE_PLATFORMS }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: docker_metadata
        name: Docker metadata
        uses: docker/metadata-action@v4.1.1
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          flavor: |
            suffix=-${{ matrix.language }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          # TODO: type=sha if retaging not possible ?

      - name: Build and push Docker image
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          build-args: |
            BASE=${{ matrix.language }}
            CDKTF_VERSION=${{ env.CDKTF_VERSION }}
          platforms: ${{ env.IMAGE_PLATFORMS }}

          # Use a temporary tag based on the commit SHA.
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ github.sha }}-${{ matrix.language }}

          labels: ${{ steps.docker_metadata.outputs.labels }}

          # The local registry does not support multi-platform images, so we can't use `load: true`.
          # See https://github.com/docker/buildx/issues/59
          # Instead we use `push: true` to push the image to a remote registry.
          push: true


      # TODO retag
      # https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#tagging-container-images
      #            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.CDKTF_VERSION }}-${{ matrix.language }}
      #            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest-${{ matrix.language }}

  #      - name: Build image
  #        run: |
  #          echo "Building image for language ${{ matrix.language }}"
  #          DOCKER_BUILDKIT=1 docker build \
  #            --build-arg "BASE=${{ matrix.language }}" \
  #            --build-arg "CDKTF_VERSION=${CDKTF_VERSION}" \
  #            --tag cdktf-bundle:${CDKTF_VERSION}-${{ matrix.language }} \
  #            --tag cdktf-bundle:latest-${{ matrix.language }} \
  #            .

  # TODO: action + propre (buildkit possible ?) ou carrément buildah
