name: CI

on:
  push:
    branches: # TODO: [ "main" ] or [ $default-branch ]
      - ci

  # Allows running this workflow manually from the Actions tab.
  # TODO TBC
  workflow_dispatch:

jobs:

  static_analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

  build_test_publish:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
