---
name: Static analysis

on:
  pull_request:
    branches:
      - "main"
      - "initial_version" # TODO: to remove

jobs:

  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: cloudposse/github-action-pre-commit@v3.0.0

  lint:
    name: lint
    permissions:
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`.
          fetch-depth: 0

      - name: Lint the code base
        uses: github/super-linter/slim@v4.9.7
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          # Declare the linters to use.
          VALIDATE_BASH: true
          VALIDATE_BASH_EXEC: true
          ERROR_ON_MISSING_EXEC_BIT: true
          VALIDATE_DOCKERFILE_HADOLINT: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_GO: true
          VALIDATE_JSON: true
          VALIDATE_MARKDOWN: true
          VALIDATE_PYTHON_BLACK: true
          VALIDATE_PYTHON_FLAKE8: true
          VALIDATE_PYTHON_ISORT: true
          VALIDATE_PYTHON_MYPY: true
          VALIDATE_PYTHON_PYLINT: true
          VALIDATE_SHELL_SHFMT: true
          VALIDATE_YAML: true
          YAML_CONFIG_FILE: .yamllint.yml
          YAML_ERROR_ON_WARNING: true
